name: Gradient-CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: olafurpg/setup-scala@v11
        with:
          distribution: temurin
          java-version: 22
      - run: sbt -v +test
